### ISSUE TITLE
Add pause option

### ISSUE THREAD

**Issue by machitgarha** [unobserved-io/Furtherance#104]
When working in Pomodoro, I sometimes want to pause the timer without being reset. Adding a pause button would help me in this case.

P.S.: Thanks for this good and simple application!

**Comment by lakoliu** [comment]
Thanks for the kind words, and for taking the time to make a suggestion. I think this is a good idea when using Furtherance as a pomodoro timer. To prevent clutter for users who may not need it, I think it would be good to be able to enable and disable the pause button in the settings. I will get to work on this as soon as I get a chance 🙂

**Comment by lakoliu** [comment]
I've looked into this a lot, and unfortunately it's just not going to be possible (at least, I don't believe it is at this time) due to the way Furtherance stores data. All tasks are stored using a start and stop time, and that's how the total time is calculated. A pause button throws a wrench into that since the correct time can no longer be calculated if it was paused for any length of time (since only the start and stop times are saved). Changing this in any way would screw up current databases across platforms. 

Sorry for the bad news, but I'm going to have to close this as not possible for now. I'll keep it in mind though in case I can come up with a solution.

**Comment by machitgarha** [comment]
A simple solution would be, if the pause button is pressed, then a new record is added to the database, but in UI the remaining time is still there. If the button (changed to a resume button) is pressed again, a new record starts to be created, and so on.

Isn't this possible?

**Comment by lakoliu** [comment]
That's a really good idea, I hadn't thought of that. The only issue would be that it would be stored as two separate tasks, but I guess that doesn't really matter. I will go ahead and re-open this and get to work on it. Thanks!

**Comment by thenesterov** [comment]
Are there any news here?

**Comment by machitgarha** [comment]
At the time, I wanted to work for 50 minutes for example, and sometimes I wanted to pause it for one or two minutes, so that I wouldn't lose my 50 minutes focus time. I know focusing continuously contradicts with pausing the work, but this was what I needed.

**P.S.:** Sorry for the late answer.

**Comment by rickykresslein** [comment]
Thanks. I will keep this in the list of considered future features, but as of now I do not plan to implement it.
