### ISSUE TITLE
Date and Time selection

### ISSUE THREAD

**Issue by tobehn** [unobserved-io/Furtherance#106]
In other gnome apps like calender they use another type of date and time selection.
Sometimes i have to adjust my tasks by editing the time.

In gnome calender they have these selection fields which are more accessible imho as they can be used with scrolling too.
![Bildschirmfoto vom 2023-03-30 17-17-11](https://user-images.githubusercontent.com/40893107/229178781-82ec29d0-3a14-4002-9906-c0ef95788ddb.png)

This is the current Furtherance implementation.

![Bildschirmfoto vom 2023-03-31 18-37-04](https://user-images.githubusercontent.com/40893107/229179240-f826f053-dd54-4dc2-a8c3-3d606ade200c.png)

I think this would be a nice enhancement. 
How about you?

**Comment by lakoliu** [comment]
Yeah, I think those look good! I'll look into the possibility of implementing that type of date & time picker in Furtherance. The expandable section style in the example you provided may be necessary to keep it from being too big. Thanks!

**Comment by lakoliu** [comment]
_Update:_ I looked into this more and found that the Gnome Calendar team created a custom widget to do this type of calendar drop-down (I believe this is the correct [link](https://gitlab.gnome.org/GNOME/gnome-calendar/-/blob/main/src/gui/event-editor/gcal-date-chooser.ui)). Unfortunately, I just don't have the time to do that at the moment, but it would be awesome if someone else could take a stab at it or if anyone can find the code of another open-source gtk-rs project that has done something similar and can be replicated with less effort. I will come back to this when I have a bit more time on my hands.

**Comment by corebots** [comment]
Hello, it would be very nice if would get some attention in the future. In addition, I'd like to suggest/report the following:

1. please add the ability to change the total time as well, i don't think it matters whether the start time would be pushed back in that case or the end time further, but being able to just set the tasks total time later would be great!

2. currently, when I use font scaling (like on a 4k screen) it's a bit cumbersome to edit the time since the string is larger than the input field, see:
![image](https://github.com/lakoliu/Furtherance/assets/12252430/a5b80989-62b5-49d6-b691-9cab4587bf0f)

3. ability to use up/down arrows would be nice (to increase/decrease the time - perhaps this is already part of the calendar widgets mentioned above, don't know)

PS I can shoot these in as separate issues if that's more desirable

**Comment by rickykresslein** [comment]
This has been changed in the new Iced re-write to use the date/time picker from iced_aw, which is much easier than typing the date and time.
