### ISSUE TITLE
CalDAV synchronization

### ISSUE THREAD

**Issue by azmeuk** [unobserved-io/Furtherance#143]
Hi. As a professional developer I work on multiple projects from multiple computers (a professional desktop at work, a personal desktop at home, and a laptop for traveling). At the end of the week I have to track the time passed on the different projects, and working from several computers at several places makes it hard. For my use case, synchronization would be a bliss.

I would love if Furtherance could read and save its data in a CalDAV calendar, so I could have the same data no matter which computer I am using.

What do you think?

**Comment by rickykresslein** [comment]
That's a good idea for syncing. I've used CalDAV but haven't created anything with it before, so I'm not familiar with exactly how it works, but I will look into it. I am currently considering a major upgrade to Furtherance that would be focused on multi-device, cross-platform syncing, so that may be coming.
As for now, you can put your Furtherance database in cloud storage to sync it to multiple devices that way.

**Comment by rickykresslein** [comment]
Now the the Iced re-write is nearly complete, I've decided on a future syncing system which will not include CalDAV. I'm still deciding on the details, but there will definitely be a self-hosted option.
