### ISSUE TITLE
Where can i find furtherance on ios

### ISSUE THREAD

**Issue by DoctorSaikesi** [unobserved-io/Furtherance#158]
I heard there is an ios version for this app, but i cannot find it.

**Comment by rickykresslein** [comment]
Unfortunately, the app is no longer available on the App Store. I removed it because it no longer matched up with the current version (different database, feature set, etc.). If you would like to install it on your iPhone you will need to do so from Xcode. You can download the source code [here](https://github.com/unobserved-io/furtherance-swiftui/tree/ios) (make sure you are on the `ios` branch), then open the project in Xcode, and in Xcode make sure it is set to your iPhone at the top and click Run (play button). That will install it on your phone and it will remain there until you remove it.

I do plan on releasing it again on mobile in the future, but that's still a long way in the future.

**Comment by DoctorSaikesi** [comment]
Thanks for the reply, guess it won't be much use for me to install on phone if it cannot sync with the desktop app. Good luck!
